zalando-stups/taupage

- create-ami.sh
I run into some issues while running create-ami.sh because the script doesn't specify which shell is compatible, is this a bash script or zsh or something else?
Are you guys running it on Linux or OSX only?
Thanks
> Clarify which shell is needed to avoid portability issues

- runtime/opt/zalando/init.d/10-prepare-disks.py
When mounting databases, we want to specify options like nobarrier or noatime to increase FS performance.
> add support for specifying options when mounting filesystems

- runtime/opt/zalando/init.d/81-register-scalyr-agent.sh
Introduce 'scalyr_application_log_parser' in the user data to set the parser name. Fixes issue #42.
> [scalyr] Make log parser configurable (fixes #42)

- runtime/opt/taupage/runtime/Docker
Add networking option for starting the docker container with different network settings
such as to add an option like
--net=host
ref. #48
> Add networking option for starting the docker container with different network settings

- config-stups-example.sh
- create-ami.sh
We would like to pass arguments like "-i" to specify a specific ssh key to be used. The most generic and backwards compatible solution was to move ssh_args to config.
> make ssh args configurable

- runtime/opt/taupage/runtime/Docker
Now it is possible to run docker with --privileged option if in taupage.yaml the privileged attribute is true.
> privileged support added.

- volume_testing.sh
And we use /bin/bash if we are not 100% sure that it has to be POSIX sh compatible (Ubuntu uses dash by default)
> tr complained about illegal byte sequence on my Mac

- runtime/opt/taupage/bin/register-in-etcd.py
- runtime/opt/taupage/runtime/Docker.py
Protocol can be specifyed either from the host side or from the docker
side.
ports:
8301: 8301
8301/udp: 8301
8500: 8500
8600: 8600/udp
> Add support of non-tcp protocols for docker port-mapping

- runtime/opt/taupage/init.d/10-prepare-disks.py
- test-userdata.yaml
- volume_testing.sh
On some corner cases the has_filesystem call could result in undesired initialization of volumes (While waiting for stabilization).
The feature was too risky and this PR suggest this to be explicit
Also made `partition` optional for cases where only host/container folder mapping is wanted
> Removed automatic initialization of devices

- create-ami.sh
- test.sh
If anything fails during build or test of the taupage ami, the used ec2 instances remain active. I propose to cleanup finally if anything went wrong. The traps should do the job.
> Finally terminate instances on failed builds

- runtime/opt/taupage/init.d/10-prepare-disks.py
Build option should be used only for compatibility with old systems and does not support all levels, in particular, level 10.
> Use --create instead of --build mdadm option when creating a new RAID array. 

- runtime/opt/taupage/init.d/10-prepare-disks.py
--create supports creating RAID10 arrays.
Make sure mdam does not complain about older boot loaders by supplying --run option.
> Use --create with mdadm instead of --build

- runtime/opt/taupage/init.d/03-push-taupage-yaml.py
Otherwise it could be the case that we cannot obtain a valid token due to rate limiting.
> Retry 3 times when pushing taupage yaml

- runtime/opt/taupage/runtime/Docker.py
This would be a proposal, which should solve the issue we've had. This lets users optionally use ``mount_var_log`` if it is set to ``true``.
@apfeiffer85 or/and @hjacobs please review.
This should fix https://github.com/zalando-stups/taupage/issues/110
> mount log directory as read-only

- runtime/opt/taupage/runtime/Docker.py
- test-userdata.yaml
This adds a new boolean options to taupage config `mount_certs: <true|false>`
This options behaves like the existing `mount_varlog` option.
Since Taupage already bundles a standard SSL certificates tree it helps application maintainers that want to use upstream images like busybox, which are very lightweight, but still need a valid certificate tree to operate correctly.
Most people just take the easy route which is to start from the zalando-ubuntu image but this adds hundreds of unnecessary MBs when the same can be achieved with only a couple MBs. This also helps Pierone
We've tested this approach with our Golang binary, using `FROM busybox:ubuntu-14.04`, which resulted in a 16MB container
I've discussed this with @sarnowski already and I'd like you guys to consider this suggestion.
> Added mount_certs option

- runtime/opt/taupage/init.d/04-enhanced-cloudwatch-metrics.sh
Currently permissions for the cron.d file are following:
-rw-rw-r-- 1 root root 198 Dec 29 12:46 /etc/cron.d/mon-put-instance-data-cloudwatch
That causes cron execution to fail - actually it is not executed at all.
Dec 29 09:03:02 ip-172-31-170-215 cron[1149]: (*system*mon-put-instance-data-cloudwatch) INSECURE MODE (group/other writable) (/etc/cron.d/mon-put-instance-data-cloudwatch)
Fixed by adding chmod 600
> chmod 600 to mon-put-instance-data-cloudwatch in cron.d

- runtime/etc/logrotate.d/application
- runtime/opt/taupage/init.d/86-adjust-application-logrotate
Addresses issue #172 
in commit ce88fc7 the possibility to rotate on size was introduced.
However, the default is still that it only rotates on time. As the space for Taupage is limited, it might be best to limit the size of any single log to a decent amount.
With a rotate of 4, diskspace for Taupage being limited to a few GB, I would propose to change the
default from none to 256M
> Set defaults for logrotate size for application.log

- runtime/etc/init/node_exporter.conf
- tests/spec/localhost/prometheus_spec.rb
Adds tcpstat to the default prometheus plugin list, in order to see summary number of TCP connections.
Adds service running requirement to rspec test (it wasn't verified if works fine - test procedure is not described in `README.md`, i wasn't able to run serverspec on my own).
> Node exporter - enable tcpstat collector, add test

- runtime/opt/taupage/init.d/10-prepare-disks.py
Also avoid hiding function dir_exists() with local variables of the same name.
Fixes #183
> Format partition if mount point doesn't exist

- test.sh
The test you built here seems incorrect, since curl will not exit with a non-zero exit code unless you request this explicitly.
-f, --fail
(HTTP) Fail silently (no output at all) on server errors. This is
mostly done to better  enable  scripts  etc  to  better  deal
with  failed attempts. In normal cases when an HTTP server fails
to deliver a document, it returns an HTML document stating so
(which often also describes why and more). This flag will prevent
curl from outputting that and return error 22.
This method is not fail-safe and there are occasions where
non-successful response codes will slip through, especially when
authentication is involved (response codes 401 and 407).
```
% curl --fail http://google.de/invalid
curl: (22) The requested URL returned error: 404 Not Found
% echo $? …
```
> fix curl call to return with non-zero in case of error

- runtime/opt/taupage/init.d/06-update-sysctl.py
Tuning applications on top of Taupage sometimes requires tuning certain (kernel)
parameters. This allows Taupage configurations to have a sysctl section which
will be used instead of the defaults.
As some kernel parameters may not be allowed to be tuned, only parameters
on a whitelist are allowed to be specified.
This addresses issues:
* https://github.com/zalando-stups/taupage/issues/175
* https://github.com/zalando/spilo/issues/42
> Allow certain sysctl parameters to be overridden

- test-userdata.yaml
rolling back to old testimage, because this works without problems (plankton does not). this is just a workaround until the tiny-docker-http-test image is ready to also test docker-in-docker functionality.
> #210 rolled back to tiny-docker-http-test image

- runtime/opt/taupage/runtime/Docker.py
This is a workaround for an issue with startup sequence when we
have external volumes to mount.  In case of EC2 instance restart
the Docker daemon will start prior to taupage-init and will
immediately try to start the container it was running prior to
the restart.  This will fail because the volumes are not there yet,
they are mounted as part of taupage-init script, in 10-prepare-disks.py.
Starting the container explicitly "fixes" the problem because at that
point all required initialization steps are completed.
> Start docker container if it already exists. Fix #199

- runtime/usr/lib/python2.7/dist-packages/cloudinit/handlers/zalando_ami_config.py
For the stateful applications it might be helpful to have the changes
to Taupage configurtion in the EC2 instance user data to be logged
across restarts.
Using diff with zero lines of unified context: we are only interested
in the changed values.
> Log the difference in taupage.yaml on startup

- runtime/opt/taupage/init.d/06-update-sysctl.py
We need this to configure PlanB Cassandra.  This parameter cannot be
changed from inside the Docker container.
https://issues.apache.org/jira/browse/CASSANDRA-3563
https://issues.apache.org/jira/secure/attachment/12505934/0001-increase-debian-limit.txt
> Add vm.max_map_count to sysctl whitelist

- runtime/opt/taupage/init.d/85-setup-appdynamics.sh
I want to disable the AppDynamics log parser per default. So the AppD Agents logs will not be pushed to the AppDynamics Analytics cluster anymore until you especially activate it in the JobFiles.
> disable follow AppD logfiles per default

- runtime/etc/init/appdynamics.conf
I would like to send custom metrics to the machine-agent http listener as described in:
https://docs.appdynamics.com/display/PRO41/Standalone+Machine+Agent+HTTP+Listener
Is there a possibility of adding this option by default to `appdynamics.conf` ?
> enabling appdynamics machine agent http listener

- runtime/opt/taupage/init.d/06-update-sysctl.py
There is no reason to have a whitelist, because settings are tracked in git senza repos.
To tune contrack table timeouts we need to tune socket parameters here.
> remove whitelist for setting sysctl values

- runtime/opt/taupage/init.d/10-prepare-disks.py
Volumes that should not be erased_on_boot may have been created
from different snapshots. One of the reasons to do this is to be able
to scale data stores (PostgreSQL, Cassandra) once they fill up.
What happens in this case is that the volume is resized, however the
filesystem still has the previous size.
Resizing the filesystem to the volume seems like a win, we can do
it unconditionally as resize2fs will figure out by itself whether
a resize is needed.
Addresses issue #252
> Resize mounts by default

- runtime/opt/taupage/bin/push-audit-logs.py
Used a random integer between 60 and 3500 seconds to send data, after the first of the script run, such that on shutdown it will processed without sleep.
> push-audit-logs.py should spread the requests to audit API #296

- runtime/opt/taupage/runtime/Docker.py
Set `TOKENINFO_URL` to "http://localhost:9021/oauth2/tokeninfo" if "local_planb_tokeninfo" is set.
> Set TOKENINFO_URL to localhost:9021 if Plan B Token Info runs locally

- runtime/opt/taupage/runtime/Docker.py
"tokeninfo_url" was ending up as "http://localhost:9021//oauth2/tokeninfo
> fixed base url for token_info

- runtime/opt/taupage/init.d/10-prepare-disks.py
- Increase default wait timeout to 60 seconds.
- Exit with error code if the device doesn't appear after timeout.
> Wait for devices to become available more reliably

- runtime/opt/taupage/init.d/10-prepare-disks.py
Fixes #318.
Blow up if the user mistakenly enters a string in the user data YAML for `erase_on_boot` parameter.
This will prevent "frequent" errors like putting the string "false" into the YAML (non-empty string evaluates to `True`).
> #318 blow up on human error (wrong type in YAML)

- build/setup.d/20-install-packages.sh
While this does not break the build, it's a bug that should be fixed
> add yaml-dev for building python yaml dependency with pip

- runtime/opt/taupage/init.d/10-prepare-disks.py
Do not format for e2fsck with exitcode 8, because our Go-CD pipeline server was deleted, because of that
> Do not format for e2fsck with exitcode 8

- runtime/opt/taupage/init.d/10-prepare-disks.py
Only require a client when actually needed, avoid doing that on script
startup: instances running without any role assigned will just have an
exception there.
> Fix use of EC2 client in prepare disks script

- build/setup.d/10-upgrade-base.sh
dkms.conf: Error! No 'PACKAGE_NAME' directive specified.
> bugfix: forgot to rename drv->module when refactoring

- build/setup.d/10-upgrade-base.sh
wrong version was set and source directory was also wrong
It was causing module build to fail silently...
> bugfix: fix dkms.config for ENA

- build/setup.d/10-upgrade-base.sh
- build/setup.d/20-install-packages.sh
- build/setup.d/89-remove-packages.sh
AWS recommend to run Ubuntu 16.04 for NVMe support: http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ssd-instance-store.html
We don't want to change base image, but it make sense at least upgrade kernel to xenial.
> Kernel upgrade: utopic->xenial

- build/setup.d/71-install-cloudwatch-logs-agent.sh
The latest version is broken for us, so revert to 1.3.9..
```
08:55:41.719 --2017-05-09 08:55:41--  https://s3.amazonaws.com/aws-cloudwatch/downloads/latest/awslogs-agent-setup.py
08:55:41.723 Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.216.32.3
08:55:41.812 Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.216.32.3|:443... connected.
08:55:42.099 HTTP request sent, awaiting response... 200 OK
08:55:42.099 Length: 54087 (53K) [text/x-python-script]
08:55:42.099 Saving to: ‘awslogs-agent-setup.py’
08:55:42.188 
08:55:42.276      0K .......... .......... .......... .......... .......... 94%  283K 0s
08:55:42.277     50K ..                                                    100% 50.5M=0.2s
08:55:42.277 
08:55:42.277 2017-05-09 08:55:42 (299 KB/s) - ‘awslogs-agent-setup.py’ saved …
```
> revert awslogs installer to 1.3.9

- build/files
- runtime/etc/logrotate.d/docker
Logrotation introduced in #397 was not working because of wrong file permission of the logrotate file and an invalid size definition.
This fixes the logrotation also for etcd which also had the wrong file permissions (introduced in #355)
> Fix logrotation for docker and etcd

- runtime/opt/taupage/init.d/01-register-scalyr-agent.sh
Modify the Scalyr Agent config to read the log files from the beginning and not just only the last / latest log lines. This will fix #402
> add copy_from_start to Scalyr Agent config - this will fix #402

- test-batchdata.yaml
- test-userdata.yaml
Use images which are build and served in a compliant way. E.g. has correct scm-source.json and originates from our registry.
> Use compliant images in tests

- images/tiny-docker-http-test/Dockerfile
- images/tiny-docker-http-test/main.go
Adds the changes from this PR https://github.com/hjacobs/tiny-docker-http-test/pull/2 which we have been using since https://github.com/zalando-stups/taupage/commit/d80ccb648f0659fbbfb13037c5befce217df64ea anyway.
It uses an ubuntu base image rather than scratch, because mounting `/usr/bin/docker` like we do when running this image, does not work unless you have stuff like libpthread, libdevmapper etc. in the container.
> Fix tiny-docker-http-test image

- build/setup.d/10-upgrade-base.sh
Intel seem to have moved the location of the driver, so it now lives under a different path.
The md5sum is still the same.
Fixes builds which are currently failing because the old URL returns 404.
> Switch download url for ixgbevf driver

- runtime/opt/taupage/init.d/00-create-custom-routing.py
We have a use-case when we want to run instances in DMZ or public subnet but without public ips. Elastic ip would be assigned later to one of the instances. Without public ip instance will not be able to initialize (download docker, push logs, use AWS api, etc...). To solve this problem we need to create a separate routing table for outgoing https traffic. Such traffic would be routed to a custom nat gateway.
Mappings between subnets and nat gateways would come from UserData and populated by senza.
> Custom routing to predefined NAT when run in DMZ without public ip

- runtime/opt/taupage/init.d/10-prepare-disks.py
If devices were already part of existing raid, kernel could build the raid automatically. In this case we can't create the new one with mdadm.
Also use the right name when performing check that device is already attached.
> Wait for devices before checking that raid exists

- runtime/opt/taupage/init.d/10-prepare-disks.py
Discard is useful only for SSD volumes, but all instance volumes already discarded by AWS, so it doesn't make sense to discard it second time.
> Format partition with nodiscard

- runtime/opt/taupage/init.d/00-create-custom-routing.py
To prevent multiple instances of the program from running concurrently, an attempt will be made to obtain an exclusive lock at launch. By default, the program will exit if the lock cannot be obtained.
Without `-w` iptables could fail with:
```
"Another app is currently holding the xtables lock. Perhaps you want to use the -w option?"
```
> Call iptables with -w argument

- runtime/opt/taupage/init.d/10-prepare-disks.py
* Bugfix: extended-options formatting options were not applied when container was starting as a root user.
* Do 3 attempts with 60 seconds interval to find "available" volumes
> Nodiscard and 3 attempts to find volumes

- runtime/opt/taupage/init.d/00-create-custom-routing.py
if node is running in public subnet without public ip it can't sync time because ntp servers are not reachable.
For ntp traffic we will do the same trick as for https, i.e. send it via NAT-GW
> Send ntp traffic via NAT-GW

- runtime/opt/taupage/init.sh
Scripts in init.d folder are started and should return the adapted error message in case the fail at some point.
> error message adaption

- build/setup.d/11-remove-unneeded-packages.sh
- runtime/etc/apt/apt.conf.d/99-disable-periodic
As reported previously (#434), this can consume a lot of resources on small instances and cause the ASG to terminate instances. We don't need this, so let's just disable the corresponding cronjobs.
Additionally, stuff like `popularity-contest` should probably not run on our production instances, so let's remove that as well.
Fix #434, #439.
> Disable periodic apt updates

- build/setup.d/11-remove-unneeded-packages.sh
The `setup.d` scripts are just sourced with `.`, not started normally. This means we shouldn't change options, otherwise we might break something else.
> Remove shell options from remove-unattended-packages.sh

- runtime/etc/crontab
This adds the crontab from a running system and changes the startup time from daily/weekly/monthly from 6:XX UTC to 1:XX UTC.
This should fix #440
> Change cron start

- runtime/opt/taupage/runtime/Docker.py
Enable usage of `--shm-size` within senza definition files.
> Add support to --shm-size in docker configuration

- build/files
File permissions were broken in the previous change, restore to sane values.
> Fix permissions on /etc/cron.d/logrotate

- build/setup.d/95-nvidia.sh
Version bump of nvidia-driver to 384.81 support Tesla V100 cards used in AWS p3 instances
> Update nvidia-driver to support Tesla Volta cards

- runtime/opt/taupage/init.d/85-setup-appdynamics.sh
A memory leak issue was reported in NodeJs application agent for which appdynamics has suggested to reduce process snapshots to 0 explicitly in agent configuration. This pull request is raised to add a config parameter (NODEJS_SNAPSHOT=$config_nodejs_disable_snapshots) in senza yaml. 
Tested it locally in a stubbed environment and the code snippet updates the config.json properly.
Can we release the AMI to only monitoring-appdynamics account before releasing it to the effected team(s).
> Configuration parameter to disable taking process snapshots on Nodejs

- build/setup.d/95-nvidia.sh
The checksum validation code used `-ne` instead of `!=` and because the hashes couldn't be parsed as numbers it always worked no matter what. Fix it so it actually validates something.
> Fix nvidia checksum validation

- build/setup.d/10-upgrade-base.sh
m5/c5 instances weren't supported because the rather old initramfs configuration we have didn't have the `nvme` module and m5/c5 use NVMe for the root volumes as well. Fix #482.
> initramfs: add nvme support for booting on c5/m5 instances

- share-ami.sh
This doesn't work with our build pipeline. :(
> Fix share-ami.sh so we don't have to use empty CHANNEL

- build/setup.d/55-setup-taupage-yaml.sh
- runtime/etc/init/planb-tokeninfo.conf
Local planb-tokeninfo service takes into account ENABLE_INTROSPECTION environment variable. However currently there is no way for users to override it (taupage config variable doesn't get propagated to the startup script).
> #489 allow enabling introspection for planb-tokeninfo service

- runtime/etc/ntp.conf
Use the default config with only the servers changed.
Fix #475.
> Update ntp.conf to use AWS Time Sync Service

- build/setup.d/55-setup-taupage-yaml.sh
- runtime/etc/init/planb-tokeninfo.conf
for enabling introspection, remove faulty support
> #489 make taupage config option naming consistent 

- runtime/opt/taupage/init.d/01-register-scalyr-agent.sh
- runtime/opt/taupage/init.d/04-configure-rsyslogd.sh
If `rsyslog_aws_metadata` is set in Taupage config, add AWS account ID and region to the log lines. This is useful for Scalyr S3 archival, because it only exports the raw log lines which means it's impossible to determine which account the message came from.
> syslog: optionally add AWS metadata to the logs

- runtime/opt/taupage/init.d/00-create-custom-routing.py
Commit https://github.com/zalando-stups/taupage/commit/36907ee43133cc49d068efbad19737ab58a95077 introduced `AWS Time Sync Service` running on 169.254.169.123, which is ip of a hypervisor.
It broke DMZ deployments without public ip.
> Don't send ntp traffic via NAT-GW

- runtime/opt/taupage/runtime/Docker.py
This updates and intends to simplify https://github.com/zalando-stups/taupage/pull/502 by using PierOne's API client to parse and check the docker image for the trusted header.
See the final diff with master here: https://github.com/zalando-stups/taupage/compare/trusted-image-check-2
> enforce images to be trusted before running them

- runtime/opt/taupage/runtime/Docker.py
Add a simple check if the image is trusted in the Docker registry before running it. This is done by parsing the image tag and checking for the `X-Trusted: true` header in the image manifest response. Note that this only applies to the "main" container that's started by Taupage, enforcing it for all pulls would break a lot of things like CI containers.
An additional benefit is that this change would also make it impossible to run images from registries other than Pier One since they don't send the header in the first place. This is already a compliance requirement, but there's a bit more enforcement now.
> Implement trusted image validation

- runtime/opt/taupage/runtime/Docker.py
Reverts zalando-stups/taupage#502
https://github.com/zalando-stups/taupage/pull/504 introduced a bug that was merged into #502 and then merged to master which breaks pulling images from closed-source PierOne. 😧
Since trusted image policy enforcement is postponed this reverts the whole thing in favour of a possible https://github.com/zalando-stups/taupage/pull/505 at some point. :kissing_heart:
/cc @aermakov-zalando
> Revert "Implement trusted image validation"

- tests/spec/localhost/td-agent_spec.rb
This fixes a syntax error:
```
14:22:37.745 
14:22:37.745 An error occurred while loading ./spec/localhost/td-agent_spec.rb.
14:22:37.745 On host `localhost'
14:22:37.745 Failure/Error: __send__(method, file)
14:22:37.745 SyntaxError:
14:22:37.745   /tmp/tests/spec/localhost/td-agent_spec.rb:25: syntax error, unexpected ')', expecting end-of-input
```
Signed-off-by: Felix Mueller <felix.mueller@zalando.de>
> Remove bracket

- test-userdata.yaml
In order to properly test https://github.com/zalando-stups/taupage/blob/master/tests/spec/localhost/scalyr-agent_spec.rb a (dummy) key actually needs to be configured.
Signed-off-by: Felix Mueller <felix.mueller@zalando.de>
> Adding dummy Scalyr Key for test

- runtime/opt/taupage/runtime/Docker.py
If the `environment` config is set to `null` then the check for secret environment variables fails. This PR fixes that edge case.
Signed-off-by: Arjun Naik <arjun.rn@gmail.com>
> Handle environment config which is none

- runtime/opt/taupage/runtime/Docker.py
The #519 change added masking of all KMS encrypted values. But the error message which prints the command was not updated to use the updated function, which causes and exception. This PR fixes the issue.
> Fix the function call when docker start fails

- runtime/opt/taupage/init.d/02-register-td-agent.py
Fix for #532 
Signed-off-by: Veit Wiessner <veit.wiessner@zalando.de>
> Fix: destination for custom log was not set correctly in fluentd config

- runtime/opt/taupage/init.d/01-register-scalyr-agent.sh
- runtime/opt/taupage/init.d/04-configure-rsyslogd.sh
This Pull-Request by default reduces redundant log output by default which is logged by application logging libraries anyways such as the date.
It also removes the Docker container ID and instance hostname and moves both over to the Scalyr server fields.
> Reduce rsyslogd output

- runtime/opt/taupage/init.d/86-adjust-application-logrotate
Compression of the previous application.log was hindering Fashion Store skipper.
This was happening despite `rotate 0`.
> Add application_logrotate_disable_compress

- build/setup.d/95-nvidia.sh
The current master cannot be built because of changes in the kernel of xenial. This driver version is the next version above and should be a significant change from the previous version.
> Upgrade Nvidia driver which is compatible with latest kernel release

- runtime/opt/taupage/init.d/01-register-scalyr-agent.sh
Any strings matching the format of a [JWT](https://tools.ietf.org/html/rfc7519) are replaced with `+++JWT_TOKEN_REDACTED+++` before they are shipped Scalyr.
> Mask JWT tokens for logs send by Scalyr Agent

- build/setup.d/07-disable-thp.sh
Set the THP to madvise to prevent overconsumption of memory in jobs with many forked processes.
> Set THP to madvise in grub

- build/setup.d/07-disable-thp.sh
The previous changes were overwritten by an Ubuntu default.
> Move the disabling to a separate file

- runtime/opt/taupage/init.sh
To prevent situations where the `cfn-signal` command fails on init when the call is done across stacks, the role is specified when executing `cfn-signal`.
The role that is used with the command needs to have the following policy attached:
```
{
"Version": "2012-10-17",
"Statement": [
{
"Effect": "Allow",
"Action": [
"cloudformation:SignalResource",
"cloudformation:DescribeStackResource"
],
"Resource": "*"
}
]
}
```
> Specifying role in cfn-signal command

- runtime/opt/taupage/init.sh
Endpoint to get the IAM Role was incorrect (missing slash).
See the `iam/security-credentials/` in [EC2 Instance metadata](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html) for additional details.
> Fixing call to get IAM Role

- runtime/opt/taupage/init.sh
> If it looks like a space, but it breaks your script, it is not a space.
In line 83, when the second operand of the OR operation is executed, the script fails with the following error message:
`taupage-init: /opt/taupage/init.sh: 83: /opt/taupage/init.sh:  cfn-signal: not found`
After multiple experiments, and hints from hard earned experienced, we identified a character in the second command that, despite every editor representing it as a blank space, it really isn't.
It is `0xc2a0` which in UTF-8 means a `NO-BREAK SPACE`.
Ref: http://www.fileformat.info/info/unicode/char/00a0/index.htm
> Fixing misleading character

- build/setup.d/07-disable-thp.sh
- build/setup.d/07-grub-settings.sh
This changes back to the old interface naming scheme (`eth*`) since some teams are relying on it.
> Use the old interface naming scheme

- runtime/opt/taupage/init.sh
Tests on the base image revealed that this extra command is not necessary.
Rolling it back.
> Rolling back extra cfn-signal command on init script

- share-ami.sh
`-u` means we can't use `-z $FOO`.
> share-ami.sh: fix -u failing

- README.md
- runtime/etc/logrotate.d/application
In order to not lose any logs during rotation
> remove copytruncate from logrotate

- build/setup.d/20-install-packages.sh
- runtime/etc/udev/rules.d/999-aws-ebs-nvme.rules
- runtime/usr/local/bin/ebs-nvme-mapping
Use the scripts from [this repo](https://github.com/oogali/ebs-automatic-nvme-mapping) to correctly handle both old and new generation instances.
> Correctly handle volume mappings on NVME-based instances

- build/setup.d/19-install-ec2-instance-connect.sh
Verify the checksum of the downloaded tar archive.
Also `shellcheck` fixes.
> Verify checksum of downloaded eic tarfile

- build/setup.d/87-prepare-appdynamics-configuration.sh
It was relying on the secrets being initialized by another one. 🤦‍♂
> Fix appdynamics script

- build/setup.d/71-install-cloudwatch-logs-agent.sh
It looks like the ancient `pip` we have right now grabs broken versions of some of the dependencies, let's update it.
> install-cloudwatch-logs-agent: update pip first

- runtime/opt/taupage/init.d/10-prepare-disks.py
The hyphen inside key for substitution is not allowed.  Translate to keys with
underscore instead: `local_ipv4` and `public_ipv4`.
Signed-off-by: Oleksandr Shulgin <oleksandr.shulgin@zalando.de>
> Fix IPv4 address substitution
