runtime/opt/zalando/init.d/10-prepare-disks.py
Docker images should be able to write to the mounted EBS volumes.
=> Change permissions to world-writable for mount points.

runtime/etc/init/etcd.conf
This address is used as a default by etcdctl
=> Listen on http://127.0.0.1:2379

runtime/opt/taupage/init.d/10-prepare-disks.py
Don't try to format anything when filesystem == 'tmpfs' but use '-t tmpfs' option during mount.
=> Add support of tmpfs mounts.

build/files, build/setup.d/55-setup-taupage-yaml.sh, build/setup.d/71-install-cloudwatch-logs-agent.sh, create-ami.sh, runtime/etc/audit/audit.rules, runtime/etc/init/etcd.conf, runtime/etc/taupage.yaml, runtime/meta/taupage.yaml, runtime/opt/taupage/bin/configure-ssh, runtime/opt/taupage/bin/register-in-etcd.py, runtime/opt/taupage/init.d/00-register-logentries-agent.sh, runtime/opt/taupage/init.d/01-register-scalyr-agent.sh, runtime/opt/taupage/init.d/02-start-berry.sh, runtime/opt/taupage/init.d/10-prepare-disks.py, runtime/opt/taupage/init.d/14-start-etcd.sh, runtime/opt/taupage/init.d/82-register-newrelic-symond.sh, runtime/opt/taupage/init.d/84-register-newrelic-java-agent.sh, runtime/opt/taupage/init.d/85-setup-appdynamics.sh, runtime/opt/taupage/init.sh, runtime/opt/taupage/runtime/Docker.py, runtime/usr/lib/python2.7/dist-packages/cloudinit/handlers/zalando_ami_config.py, runtime/usr/local/lib/python3.4/dist-packages/taupage/__init__.py
@hjacobs Could you please have a look at this, since it's a pretty critical change?
=> Store taupage yaml in meta

runtime/opt/taupage/init.d/03-push-taupage-yaml.py, runtime/usr/local/lib/python3.4/dist-packages/taupage/__init__.py
This actually the correct place to retry, sorry.
=> Retry on get_token

runtime/usr/local/lib/python3.4/dist-packages/taupage/__init__.py
=> Fix wrong sleep time

build/setup.d/71-install-cloudwatch-logs-agent.sh, runtime/opt/taupage/init.d/04-configure-cloudwatch-logs-agent.py
Untested, please do not merge yet!
Comments appreciated.
=> #114 rename cron.d file to only run awslogs nanny when needed

.travis.yml, build/setup.d/55-setup-taupage-yaml.sh, build/setup.d/70-berry.sh, runtime/opt/taupage/runtime/Docker.py, runtime/usr/local/lib/python3.4/dist-packages/taupage/__init__.py, secret/secret-vars.sh
Untested fix for #116, for review
=> Issue 116: Use OAuth access token URL instead of Token Service by default

runtime/etc/logrotate.d/application, runtime/etc/logrotate.d/rsyslog, runtime/opt/taupage/init.d/86-adjust-application-logrotate
i also add some documentation here: https://github.com/zalando-stups/documentation/blob/master/components/taupage.rst
=> Make application.log log rotate configurable - close #107

build/setup.d/10-upgrade-base.sh
=> upgrade packages

runtime/opt/taupage/init.d/82-register-newrelic-symond.sh, runtime/opt/taupage/init.d/84-register-newrelic-java-agent.sh
* Added kms decryption from [01-register-scalyr-agent.sh](https://github.com/zalando-stups/taupage/blob/master/runtime/opt/taupage/init.d/01-register-scalyr-agent.sh#L25)
* Changed shebang to bash
=> Decrypt newrelic account key if necessary

runtime/opt/taupage/init.d/04-configure-rsyslogd.sh
Fixes https://github.com/zalando-stups/taupage/issues/164
=> Enabling to configure MaxMessageSize for ryslog

runtime/usr/local/lib/python3.4/dist-packages/taupage/__init__.py
=> Fix logger spam

build/setup.d/87-prepare-appdynamics-configuration.sh, runtime/opt/taupage/init.d/85-setup-appdynamics.sh
enables multi-tenant support for appdynamics
=> 187 appdynamics multi tenant

runtime/opt/taupage/init.d/85-setup-appdynamics.sh, tests/spec/localhost/ec2_spec.rb
=> Modify AppDynamics node name

runtime/opt/taupage/runtime/Docker.py
=> Start existing docker container if found on restart

runtime/opt/taupage/runtime/Docker.py, test-userdata.yaml, test.sh
=> #210 bind mounting missing shared libs for docker to function properly

runtime/opt/taupage/bin/push-audit-logs.py, runtime/opt/taupage/init.d/03-push-taupage-yaml.py
=> #218 use log sink

runtime/etc/rsyslog.d/25-etcd.conf
=> #226 move etcd log info

runtime/opt/taupage/init.d/85-setup-appdynamics.sh
=> fix AppDynamics integration

runtime/opt/taupage/init.d/85-setup-appdynamics.sh
=> add option to include necessary scala classes in AppDynamics 

runtime/opt/taupage/init.d/06-update-sysctl.py
=> - Add net.core.somaxconn to sysctl whitelist

runtime/opt/taupage/init.d/07-update-sysfs.py, test-userdata.yaml, tests/spec/localhost/sysfs_spec.rb
=> Support for editing sysfs paths

runtime/opt/taupage/init.d/85-setup-appdynamics.sh
for a better Appdynamics node.js Agent integration
=> #255 Appdynamics Node.js integration snippet

runtime/opt/taupage/init.d/85-setup-appdynamics.sh
We have to merge this into the master otherwise AppDynamics integration is broken :( 
Just some small stupid syntax errors.
=> fix some syntax errors

build/setup.d/87-prepare-appdynamics-configuration.sh, runtime/opt/taupage/init.d/85-setup-appdynamics.sh
add default appD account data on build process.
=> add default accountdata to node-js snippet

build/setup.d/87-prepare-appdynamics-configuration.sh, runtime/opt/taupage/init.d/85-setup-appdynamics.sh
Fix node.js AppDynamics integration
=> fix used wrong variables and runtime script was also wrong

runtime/etc/cron.d/mon-put-instance-data-cloudwatch.deactivated, runtime/opt/taupage/cloudwatch/aws-scripts-mon/AwsSignatureV4.pm, runtime/opt/taupage/cloudwatch/aws-scripts-mon/CloudWatchClient.pm, runtime/opt/taupage/cloudwatch/aws-scripts-mon/NOTICE.txt, runtime/opt/taupage/cloudwatch/aws-scripts-mon/mon-get-instance-stats.pl, runtime/opt/taupage/cloudwatch/aws-scripts-mon/mon-put-instance-data.pl
Currently cloudwatch scripts can't push memory&disk metrics using IAM role credentials. Looks like latest version of the scripts supports IAM roles. 
With this, we can create auto scaling policies based on memory usage.
https://forums.aws.amazon.com/message.jspa?messageID=422894
https://aws.amazon.com/code/8720044071969977
=> update cloudwatch scripts

runtime/etc/init/planb-tokeninfo.conf, runtime/opt/taupage/init.d/14-start-planb-tokeninfo.sh, test-userdata.yaml
Add local planb-tokeninfo to remove the rtt to an external tokeninfo service.
=> add local planb-tokeninfo

runtime/etc/cron.hourly/logrotate
This should be nicer on cpu and i/o scheduling.
Closes #292
=> Changed the hourly log rotation call 

runtime/opt/taupage/init.d/10-prepare-disks.py
=> Run e2fsck on partition if advised by resize2fs

runtime/etc/init/appdynamics.conf
This will also show special chars in the AppDynamics Log Analytics
=> add UTF-8 support to AppDynamics Machine Agent #302

runtime/opt/taupage/bin/decrypt-kms.py, runtime/opt/taupage/bin/register-in-etcd.py, runtime/opt/taupage/init.d/03-push-taupage-yaml.py, runtime/opt/taupage/init.d/04-configure-cloudwatch-logs-agent.py
=> Fix dumb failing flake8 issues

share-ami-public.sh, share-ami.sh, unshare-ami.sh
`Error parsing parameter '--launch-permission': Expected: '=', received: ':' for input:`
=> Fix parsing Error

build/setup.d/10-upgrade-base.sh
I hope it is possible to update to a newer Kernel. Please share with our DB team
=> fix know kernel issues if you have heavy write load like PG

runtime/opt/taupage/init.d/10-prepare-disks.py
Resize function doesn't need a special check for e2fsck as we are
running the check ourselves prior to mount.  Also renamed `resize` to
`extend`.
=> Rework filesystem initialization logic

build/setup.d/20-install-packages.sh
The log in our build pipeline does not show the content of log files. We are not using these files anyways so delete it
=> we want to see everything in STDOUT and not search in files

runtime/opt/taupage/init.d/10-prepare-disks.py
=> Protect format_partition() with try/except as well

build/setup.d/87-prepare-appdynamics-configuration.sh, runtime/opt/taupage/init.d/85-setup-appdynamics.sh, runtime/opt/taupage/runtime/Docker.py
This is a new Way how we can integrate the AppD Node.js Agent.
=> add new AppD node.js integration 

runtime/opt/taupage/init.d/10-prepare-disks.py
This fixes the way we decide if a volume needs to be formatted or not.
We will only format an EBS volume if it is required explicitly by the
erase_on_boot flag in the user data or if a special temporary tag is set
on the volume.  We remove such tag immediately when formatting, so that
the next time instance starts up it will not try to format again in
error.
This makes the use case of RAID volumes over multiple EBS devices not
supported unless erase_on_boot is set to True in the user data.
=> Format EBS volumes based on Tag and User Data

runtime/opt/taupage/runtime/Docker.py
Then the Developer is able to add custom AppDynamics MachineAgent extensions.
=> mount AppDynamics MachineAgent extension Directory to the Docker 

runtime/etc/logrotate.d/etcd
fixes https://github.com/zalando-stups/taupage/issues/354
=> rotate etcd logs

runtime/etc/init/planb-tokeninfo.conf
to be ready for Platform IAM tokens
=> upgrade local planb-tokeninfo

build/setup.d/10-upgrade-base.sh
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/sriov-networking.html#enhanced-networking-ubuntu
=> Install latest version of ixgbevf

build/setup.d/10-upgrade-base.sh, create-ami.sh
It's needed to enable Enhanced Networking with the Elastic Network Adapter (ENA) on Linux Instances in a VPC on instance types R4 and m4.16xlarge.
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking.html
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking-ena.html#enhanced-networking-ena-ubuntu
=> Install ena kernel module

create-ami.sh
=> bugfix: specify correct istance id

build/setup.d/10-upgrade-base.sh, build/setup.d/89-remove-packages.sh
https://github.com/zalando-stups/taupage/pull/370#commitcomment-21166480
=> Remove packages from a single place

runtime/opt/taupage/init.d/85-setup-appdynamics.sh
since Scalyr is now our central logging Provider, AppD is now per default disabled.
=> disable AppD logging per default

runtime/opt/taupage/runtime/Docker.py
https://github.com/zalando-stups/taupage/issues/381
after https://github.com/zalando-stups/pierone-cli/pull/57
=> use pierone.api.docker_login_with_iid if use_iid_auth true

runtime/etc/logrotate.d/custom, runtime/opt/taupage/init.d/01-register-scalyr-agent.sh, runtime/opt/taupage/init.d/86-adjust-application-logrotate
add custom logs to scalyr and logrotation for custom logs. 
I'll add documentation to the STUPS documentation as well. 
I'll reference this here as well. 
It will solve #387
=> add custom logs to scalyr and logrotation for custom logs

runtime/etc/logrotate.d/docker
this will fix: #396 which users already asked for in #142
=> do reasonable logrotation for docker logs

runtime/opt/taupage/init.sh, test-batchdata.yaml, test.sh
implements #78 
this is my first shot to implement the shutdown switch. In some internal tests it's looking promising. However i'm currently not sure about the test implementation and open for some suggestions.
=> WIP: initial implementation of shutdown behavior

build/setup.d/20-install-packages.sh
Added sysstat and htop packages (#400) for basic performance analysis.
=> Added sysstat and htop packages (#400) for basic performance analysis

images/tiny-docker-http-test/Makefile
Use zalando docker registry by default.
=> Use zalando docker registry

test-batchdata.yaml, test-userdata.yaml
Use latest images in the test.
=> Update test image versions

runtime/opt/taupage/init.d/10-prepare-disks.py
=> Added try execpt for erase_tag_set handling

runtime/opt/taupage/init.d/86-adjust-application-logrotate
=> make copytruncate and delaycompress behavior configurable

runtime/etc/cron.daily/logrotate
as suggested in #425 we should use nice to lower the priority
=> use nice to lower the prio for daily logrotate

runtime/opt/taupage/init.d/10-prepare-disks.py, runtime/opt/taupage/runtime/Docker.py
In busy accounts chances of throttling aws api requests are very high
=> Wrap ec2 methods into functions and retry when requests are throttled

build/setup.d/10-upgrade-base.sh
new releases contain mostly bugfixes
=> Bump ixgbevf and ena versions

build/setup.d/80-ssh-access-granting-service.sh, secret/ssh-access-granting-service.pub
We need this for key rotation in even.
=> Support multiple keys

build/setup.d/80-ssh-access-granting-service.sh
=> Fix path to grant-ssh-access-forced-command.py

build/setup.d/80-ssh-access-granting-service.sh
Maybe I should've tested this. :(
=> Use another separator char for sed

share-ami.sh
This update, should add git tags for the config repo
=> add git tag for config repo

build/setup.d/10-upgrade-base.sh
Intel changed the URL, update the download ID. Additionally, use curl --fail so it's clear why it failed.
=> Fix download links for the NIC drivers

build/setup.d/21-install-instana-agent.sh, runtime/opt/taupage/init.d/80-setup-instana-agent.sh, runtime/opt/taupage/init.sh
Don't merge. work under progress
=> added support for instana agent in taupage

build/setup.d/21-install-instana-agent.sh
removed whitespace sorrounding a '=' for quickfix
=> removed whitespace sorrounding

build/setup.d/56-install-instana-agent.sh, runtime/opt/taupage/init.d/80-setup-instana-agent.sh
fix whitespaces in bash scripts
=> fix whitespaces in bash scripts

runtime/opt/taupage/init.sh
change bash test command on init and fix whitespaces. Also changed the start command for the instana agent.
=> change bash test command on init and fix whitespaces

runtime/opt/taupage/init.d/80-setup-instana-agent.sh, runtime/opt/taupage/init.sh
=> Fix exit status

runtime/opt/taupage/init.d/01-register-scalyr-agent.sh
This is a preparation to allow setting custom Scalyr hosts.
=> Allow setting Scalyr region to "eu"

runtime/opt/taupage/init.d/01-register-scalyr-agent.sh
Fixed scalyr startup script in order to enable eu.scalyr.com
=> Created sed command for Scalyr startup

runtime/opt/taupage/bin/push-audit-logs.py, runtime/opt/taupage/bin/register-in-etcd.py, runtime/opt/taupage/init.d/03-push-taupage-yaml.py, runtime/opt/taupage/init.d/10-prepare-disks.py, runtime/opt/taupage/runtime/Docker.py, runtime/usr/local/lib/python3.4/dist-packages/taupage/__init__.py
This should fix the flake8 run.
=> Fix bare except blocks

runtime/opt/taupage/init.d/01-register-scalyr-agent.sh
Per-log attributes are counted as log volume per log line.
=> Moved common logging attributes to server_attributes

runtime/opt/taupage/runtime/Docker.py
Disallow mutable Docker image tags such as `latest` or `*-SNAPSHOT`.
Fixes #212.
=> #212 prohibit latest and SNAPSHOT Docker image tags

runtime/opt/taupage/init.d/01-register-scalyr-agent.sh
=> Enforce Logging to eu.scalyr.com

runtime/opt/taupage/init.d/04-configure-rsyslogd.sh
Right now it is not possible to change rsyslog configuration for application log. 
For us it means that we have to process log messages with additional fields, that are not needed by anyone. For example, default configuration gives us this kind of line in application.log: 
```
Jul 31 15:35:48 ip-172-31-166-196 docker/cd49ea876b3a[891]: 172.31.13.19 - - [31/Jul/2018:15:35:48 +0000] "-" POST /event-types/blablabla HTTP/1.1 200 0 141368 0.026 "172.31.140.112:8080" 0.024 "200" 1 "-" "python-requests/2.11.1" "-"
```
Here the date that is coming from rsyslog (`Jul 31 15:35:48`) and process info (`docker/cd49ea876b3a[891]`) are not needed. 
After merging this pr, it will be possible to change the format, that is used by rsyslog to actually dump message to /var/log/application.log
By setting …
=> Allow changing format of message in rsyslog configuration

build/setup.d/10-upgrade-base.sh
* ENA: add checksum verification
* ENA: update from v1.2.0 to v1.5.3
=> Update ENA drivers to v1.5.3

.travis.yml
PR tests are affected by https://github.com/travis-ci/travis-ci/issues/7940.
=> Fix Travis integration

runtime/opt/taupage/init.d/01-register-scalyr-agent.sh, runtime/opt/taupage/init.d/10-prepare-disks.py, tests/spec/localhost/scalyr-agent_spec.rb
fixed scalyr agent file pickup in /opt/taupage/init.d/01-register-scalyr-agent.sh
Signed-off-by: Veit Wiessner <veit.wiessner@zalando.de>
=> fixed scalyr agent file pickup

runtime/opt/taupage/runtime/Docker.py
This PR adds support so that all environment variables which are KMS encrypted as masked .
Signed-off-by: Arjun Naik <arjun.naik@zalando.de>
=> Added masking of KMS encrypted environment variables

scripts/serverspec.sh
Cherry-pick #516 to `master` to fix the tests.
=> Update Ruby version for ServerSpec (#516)

build/setup.d/20-install-packages.sh, build/setup.d/21-install-td-agent-packages.sh
Pinned td-agent and td-agent plugins to tested versions to prevent updates from braking the setup.
=> Pin td agent versions

test-batchdata.yaml, test-userdata.yaml
Use a trusted Docker image for the test instances so they can actually start.
=> Use trusted test images

share-ami.sh
This is (now) needed for compliance checks.
=> Automatically tag images with ExpirationTime

build/setup.d/01-add-node_exporter-text_collector-dir.sh, runtime/opt/taupage/init.d/02-register-td-agent.py, tests/spec/localhost/td-agent_spec.rb
* logs to s3 by default
* fixed fluentd checks
=> Fluentd s3 by default

runtime/opt/taupage/init.d/02-register-td-agent.py
Relied on value from config that is not there in test deployment
=> S3 default fix

build/setup.d/01-add-node_exporter-text_collector-dir.sh, runtime/opt/taupage/init.d/02-register-td-agent.py, tests/spec/localhost/td-agent_spec.rb
Temporarily revert the S3 changes so that the PR #543 can be rolled out.
=> Reverting the logging to S3 changes

build/setup.d/01-add-node_exporter-text_collector-dir.sh, runtime/etc/td-agent/templates/td-agent.conf.jinja2, runtime/opt/taupage/bin/s3-iam-check.py, runtime/opt/taupage/init.d/01-register-scalyr-agent.sh, runtime/opt/taupage/init.d/02-register-td-agent.py, tests/spec/localhost/td-agent_spec.rb
Log to S3 by default
set up a cronjob to test s3 iam permissions if s3 was chosen as log destination
=> Logging s3 by default

build/setup.d/95-nvidia.sh, test-gpudata.yaml, test.sh
Install the nvidia drivers from the Ubuntu package repositories to ensure compatibility.
=> Install the GPU drivers from package manager

runtime/opt/taupage/init.d/02-register-td-agent.py
Signed-off-by: Veit Wiessner <veit.wiessner@zalando.de>
=> changed loglevel to error

share-ami.sh
This is useful for the changelog.
=> Enable release tagging by default

build/setup.d/20-install-packages.sh
This ships fluentd in version 1.4.2
=> Update td-agent version to latest (3.4.1-0)

runtime/opt/taupage/init.d/01-register-scalyr-agent.sh
Increase max line length to 50k for scalyr agent
=> increase max line length to 50k for scalyr-agent logging

build/setup.d/55-setup-taupage-yaml.sh, runtime/etc/init/planb-tokeninfo.conf
Fixes https://github.com/zalando-stups/taupage/issues/566
=> Added environment variables required for the lightstep opentracing

build/setup.d/10-upgrade-base.sh
Cherry-pick from #565 so we can build #567.
=> Update ixgbevf version

build/setup.d/55-setup-taupage-yaml.sh, runtime/etc/init/planb-tokeninfo.conf
For https://github.com/zalando-stups/taupage/issues/566
=> Enable opentracing for tokeninfo

runtime/opt/taupage/init.d/01-register-scalyr-agent.py
Fixes for script introduced in https://github.com/zalando-stups/taupage/pull/565
=> Fix scalyr init script

build/setup.d/100-install-open-policy-agent.sh, runtime/etc/init/opa.conf, runtime/etc/opa/opa_conf.yaml, runtime/opt/taupage/init.d/92-start-opa.sh
Add open policy agent download and install
=> Add open policy agent

runtime/etc/init/opa.conf
Signed-off-by: Amit Rangra <amit.rangra@zalando.de>
Add the missing application_id for opa
=> Add application_id for opa

build/setup.d/10-upgrade-base.sh
=> Update ixgbevf to 4.6.3

runtime/etc/init/opa.conf, runtime/etc/opa/opa_conf.yaml
Signed-off-by: Nuwandi <nuwandi.wickramasinghe@zalando.de>
=> CIAM-389: Start opa with enabled authorization

build/setup.d/86-ubuntu-docker-group.sh
Users are used to running `docker ps`
=> Add ubuntu user to the docker group

build/setup.d/86-ubuntu-docker-group.sh
Signed-off-by: Arjun Naik <arjun.rn@gmail.com>
=> Check if docker group exists before creating

runtime/opt/taupage/init.d/10-prepare-disks.py
Fixes #488
Limit scope of substitutions to EBS volume names only.  This is not needed in
any other places of configuration (otherwise there would be open issues for
those as well).
Only allow `local-ipv4` and `public-ipv4` vars from instance metadata: for the
volume name substitutions these are the most useful ones.
=> Allow IPv4 address substitutions in EBS volume names
